/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// Tapdata Cloud docs list
  cloud: [
    'cloud/what-is-tapdata-cloud',
    {
     type: 'category',
     label: 'Introduction',
     link: {type: 'doc', id: 'cloud/introduction/README'},
     items: [
            'cloud/introduction/architecture',
            'cloud/introduction/features',
            'cloud/introduction/benefits',
            'cloud/introduction/use-cases',
            'cloud/introduction/supported-databases',
            'cloud/introduction/terms',
     ]
    },
{
     type: 'category',
     label: 'Billing',
     link: {type: 'doc', id: 'cloud/billing/README'},
     items: [
            'cloud/billing/billing-overview',
            'cloud/billing/purchase',
            'cloud/billing/renew-subscribe',
            'cloud/billing/expiration',
            'cloud/billing/refund',
     ]
    },
    {
     type: 'category',
     label: 'Quick Start',
     link: {type: 'doc', id: 'cloud/quick-start/README'},
     items: [
            {
             type: 'category',
             label: 'Step 1: Install Agent',
             link: {type: 'doc', id: 'cloud/quick-start/install-agent/README'},
             items: [
                    'cloud/quick-start/install-agent/agent-on-linux',
                    'cloud/quick-start/install-agent/agent-on-windows',
                    'cloud/quick-start/install-agent/agent-on-docker',
                    'cloud/quick-start/install-agent/agent-on-mac-m1',
             ]
            },
            'cloud/quick-start/connect-database',
            'cloud/quick-start/create-task',
     ]
    },
{
     type: 'category',
     label: 'Connect Data Sources',
     link: {type: 'doc', id: 'cloud/prerequisites/README'},
     items: [
             'cloud/prerequisites/allow-access-network',
             {
              type: 'category',
              label: 'Certified Databases',
              link: {type: 'doc', id: 'cloud/prerequisites/certified/README'},
              items: [
                      'cloud/prerequisites/certified/clickhouse',
                      'cloud/prerequisites/certified/kafka',
                      'cloud/prerequisites/certified/mysql',
                      'cloud/prerequisites/certified/mongodb',
                      'cloud/prerequisites/certified/oracle',
                      'cloud/prerequisites/certified/postgresql',
                      'cloud/prerequisites/certified/sqlserver',
                      ]
              },
              {
               type: 'category',
               label: 'Beta Data Source',
               link: {type: 'doc', id: 'cloud/prerequisites/beta/README'},
               items: [
                       {
                        type: 'category',
                        label: 'Databases',
                        link: {type: 'doc', id: 'cloud/prerequisites/beta/database/README'},
                         items: [
                                'cloud/prerequisites/beta/database/big-query',
                                'cloud/prerequisites/beta/database/custom-connection',
                                'cloud/prerequisites/beta/database/dameng',
                                'cloud/prerequisites/beta/database/databend',
                                'cloud/prerequisites/beta/database/db2',
                                'cloud/prerequisites/beta/database/doris',
                                'cloud/prerequisites/beta/database/dummy',
                                'cloud/prerequisites/beta/database/kingbase-es-r6',
                                'cloud/prerequisites/beta/database/mariadb',
                                'cloud/prerequisites/beta/database/redis',
                                'cloud/prerequisites/beta/database/selectdb',
                                'cloud/prerequisites/beta/database/tdengine',
                                'cloud/prerequisites/beta/database/tidb',
                                'cloud/prerequisites/beta/database/yashandb',
                                ]
                        },
                        {
                        type: 'category',
                        label: 'SaaS',
                        link: {type: 'doc', id: 'cloud/prerequisites/beta/saas/README'},
                         items: [
                                'cloud/prerequisites/beta/saas/coding',
                                'cloud/prerequisites/beta/saas/github',
                                'cloud/prerequisites/beta/saas/http-receiver',
                                'cloud/prerequisites/beta/saas/hubspot',
                                'cloud/prerequisites/beta/saas/lark-im',
                                'cloud/prerequisites/beta/saas/lark-task',
                                'cloud/prerequisites/beta/saas/metabase',
                                'cloud/prerequisites/beta/saas/salesforce',
                                'cloud/prerequisites/beta/saas/zoho-desk',
                                ]
                        },
                        {
                        type: 'category',
                        label: 'Files',
                        link: {type: 'doc', id: 'cloud/prerequisites/beta/file/README'},
                         items: [
                                'cloud/prerequisites/beta/file/csv',
                                'cloud/prerequisites/beta/file/excel',
                                ]
                        }
                       ]
               },
               {
               type: 'category',
               label: 'Alpha Data Source',
               link: {type: 'doc', id: 'cloud/prerequisites/alpha/README'},
               items: [
                       {
                        type: 'category',
                        label: 'Databases',
                        link: {type: 'doc', id: 'cloud/prerequisites/alpha/database/README'},
                         items: [
                                'cloud/prerequisites/alpha/database/activemq',
                                'cloud/prerequisites/alpha/database/aliyun-adb-mysql',
                                'cloud/prerequisites/alpha/database/aliyun-mongodb',
                                'cloud/prerequisites/alpha/database/aliyun-rds-for-mariadb',
                                'cloud/prerequisites/alpha/database/aliyun-rds-for-mongodb',
                                'cloud/prerequisites/alpha/database/aliyun-rds-for-mysql',
                                'cloud/prerequisites/alpha/database/aliyun-rds-for-pg',
                                'cloud/prerequisites/alpha/database/amazon-rds-mysql',
                                'cloud/prerequisites/alpha/database/elasticsearch',
                                'cloud/prerequisites/alpha/database/gbase-8a',
                                'cloud/prerequisites/alpha/database/gbase-8s',
                                'cloud/prerequisites/alpha/database/hazelcast-cloud',
                                'cloud/prerequisites/alpha/database/hive1',
                                'cloud/prerequisites/alpha/database/hive3',
                                'cloud/prerequisites/alpha/database/kingbase-es-r3',
                                'cloud/prerequisites/alpha/database/mrs-hive3',
                                'cloud/prerequisites/alpha/database/mysql-pxc',
                                'cloud/prerequisites/alpha/database/oceanbase',
                                'cloud/prerequisites/alpha/database/opengauss',
                                'cloud/prerequisites/alpha/database/polardb-mysql',
                                'cloud/prerequisites/alpha/database/polardb-postgresql',
                                'cloud/prerequisites/alpha/database/rabbitmq',
                                'cloud/prerequisites/alpha/database/rocketmq',
                                'cloud/prerequisites/alpha/database/tablestore',
                                'cloud/prerequisites/alpha/database/tencentdb-for-mariadb',
                                'cloud/prerequisites/alpha/database/tencentdb-for-mongodb',
                                'cloud/prerequisites/alpha/database/tencentdb-for-mysql',
                                'cloud/prerequisites/alpha/database/tencentdb-for-pg',
                                ]
                       },
                       {
                        type: 'category',
                        label: 'SaaS',
                        link: {type: 'doc', id: 'cloud/prerequisites/alpha/saas/README'},
                         items: [
                                'cloud/prerequisites/alpha/saas/ai-chat',
                                'cloud/prerequisites/alpha/saas/bes-channels',
                                'cloud/prerequisites/alpha/saas/lark-approval',
                                'cloud/prerequisites/alpha/saas/lark-doc',
                                'cloud/prerequisites/alpha/saas/quick-api',
                                'cloud/prerequisites/alpha/saas/shein',
                                'cloud/prerequisites/alpha/saas/vika',
                                'cloud/prerequisites/alpha/saas/zoho-crm',
                                ]
                       },
                       {
                        type: 'category',
                        label: 'Files',
                        link: {type: 'doc', id: 'cloud/prerequisites/alpha/file/README'},
                         items: [
                                'cloud/prerequisites/alpha/file/json',
                                'cloud/prerequisites/alpha/file/xml',
                                ]
                       },
                       ]
               },
     ]
    },
    {
     type: 'category',
     label: 'User Guide',
     link: {type: 'doc', id: 'cloud/user-guide/README'},
     items: [
             'cloud/user-guide/workshop',
             'cloud/user-guide/manage-agent',
             'cloud/user-guide/manage-connection',
             {
              type: 'category',
              label: 'Data Replication',
              link: {type: 'doc', id: 'cloud/user-guide/copy-data/README'},
              items:[
                    'cloud/user-guide/copy-data/create-task',
                    'cloud/user-guide/copy-data/manage-task',
                    'cloud/user-guide/copy-data/monitor-task',
                    ]
            },
            {
             type: 'category',
             label: 'Data Development(Beta',
             link: {type: 'doc', id: 'cloud/user-guide/data-development/README'},
             items:[
                   'cloud/user-guide/data-development/create-task',
                   'cloud/user-guide/data-development/manage-task',
                   'cloud/user-guide/data-development/process-node',
                   'cloud/user-guide/data-development/monitor-task',
                   ]
             },
             'cloud/user-guide/custom-node',
             'cloud/user-guide/operation-log',
             {
              type: 'category',
              label: 'Data Console(Beta)',
              link: {type: 'doc', id: 'cloud/user-guide/data-console/README'},
              items:[
                    {
                     type: 'category',
                     label: 'Data Integration Mode',
                     link: {type: 'doc', id: 'cloud/user-guide/data-console/etl-mode/README'},
                     items:[
                            'cloud/user-guide/data-console/etl-mode/etl-mode-dashboard',
                            'cloud/user-guide/data-console/etl-mode/create-etl-task',
                           ]
                    },
                    {
                     type: 'category',
                     label: 'Data Service Platform Model',
                     link: {type: 'doc', id: 'cloud/user-guide/data-console/daas-mode/README'},
                     items:[
                            'cloud/user-guide/data-console/daas-mode/enable-daas-mode',
                            'cloud/user-guide/data-console/daas-mode/daas-mode-dashboard',
                            'cloud/user-guide/data-console/daas-mode/create-daas-task',
                           ]
                    },
                    ]
             },               
             'cloud/user-guide/trouble-shooting-connection',
             'cloud/user-guide/no-supported-data-type',
            ]
    },
    {
     type: 'category',
     label: 'Tutorials',
     link: {type: 'doc', id: 'cloud/best-practice/README'},
     items: [
            'cloud/best-practice/mysql-to-bigquery',
            'cloud/best-practice/oracle-to-tablestore',
            'cloud/best-practice/excel-to-mysql',
            
        ]
        },
     {
      type: 'category',
      label: 'FAQ',
      link: {type: 'doc', id: 'cloud/faq/README'},
      items:[
             'cloud/faq/data-security',
             'cloud/faq/agent-installation',
             'cloud/faq/database',
             'cloud/faq/task',
      ]
     },
     {
      type: 'category',
      label: 'Appendix',
      link: {type: 'doc', id: 'cloud/appendix/README'},
      items: [
              'cloud/appendix/standard-js',
              'cloud/appendix/enhanced-js'
              ]
     },
  ],
};


module.exports = sidebars;
