/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// Tapdata Cloud docs list
  cloud: [
    'cloud/what-is-tapdata-cloud',
    {
     type: 'category',
     label: 'Introduction',
     link: {type: 'doc', id: 'cloud/introduction/README'},
     items: [
            'cloud/introduction/architecture',
            'cloud/introduction/features',
            'cloud/introduction/benefits',
            'cloud/introduction/use-cases',
            'cloud/introduction/supported-databases',
            'cloud/introduction/terms',
     ]
    },
{
     type: 'category',
     label: 'Billing',
     link: {type: 'doc', id: 'cloud/billing/README'},
     items: [
            'cloud/billing/billing-overview',
            'cloud/billing/purchase',
            'cloud/billing/renew-subscribe',
            'cloud/billing/expiration',
            'cloud/billing/refund',
     ]
    },
    {
     type: 'category',
     label: 'Quick Start',
     link: {type: 'doc', id: 'cloud/quick-start/README'},
     items: [
            {
             type: 'category',
             label: 'Step 1: Install Agent',
             link: {type: 'doc', id: 'cloud/quick-start/install-agent/README'},
             items: [
                    'cloud/quick-start/install-agent/agent-on-linux',
                    'cloud/quick-start/install-agent/agent-on-windows',
                    'cloud/quick-start/install-agent/agent-on-docker',
                    'cloud/quick-start/install-agent/agent-on-mac-m1',
             ]
            },
            'cloud/quick-start/connect-database',
            'cloud/quick-start/create-task',
     ]
    },
    {
     type: 'category',
     label: 'Preparations',
     link: {type: 'doc', id: 'cloud/prerequisites/README'},
     items: [
             'cloud/prerequisites/allow-access-network',
            {
             type: 'category',
             label: 'Configure Database and Grant Access',
             link: {type: 'doc', id: 'cloud/prerequisites/config-database/README'},
             items: [
                    {
                       type: 'category',
                       label: 'GA Data Sources',
                       link: {type: 'doc', id: 'cloud/prerequisites/config-database/certified/README'},
                       items: [
                              'cloud/prerequisites/config-database/certified/clickhouse',
                              'cloud/prerequisites/config-database/certified/kafka',
                              'cloud/prerequisites/config-database/certified/mysql',
                              'cloud/prerequisites/config-database/certified/mongodb',
                              'cloud/prerequisites/config-database/certified/oracle',
                              'cloud/prerequisites/config-database/certified/postgresql',
                              'cloud/prerequisites/config-database/certified/sqlserver',
                       ]
                      },
                      {
                       type: 'category',
                       label: 'Beta Data Sources',
                       link: {type: 'doc', id: 'cloud/prerequisites/config-database/beta/README'},
                       items: [
                              'cloud/prerequisites/config-database/beta/csv-and-excel',
                              'cloud/prerequisites/config-database/beta/mongodb-atlas',
                       ]
                      },
                      {
                       type: 'category',
                       label: 'Alpha Data Sources',
                       link: {type: 'doc', id: 'cloud/prerequisites/config-database/alpha/README'},
                       items: [
                              'cloud/prerequisites/config-database/alpha/json-and-xml',
                              'cloud/prerequisites/config-database/alpha/zoho-crm',
                       ]
                      },                                            
             ]
            },
     ]
    },
    {
     type: 'category',
     label: 'User Guide',
     link: {type: 'doc', id: 'cloud/user-guide/README'},
     items: [
             'cloud/user-guide/workshop',
             'cloud/user-guide/manage-agent',
             {
              type: 'category',
              label: 'Connect Data Sources',
              link: {type: 'doc', id: 'cloud/user-guide/connect-database/README'},
              items:[
                    {
                     type: 'category',
                     label: 'GA Data Sources',
                     link: {type: 'doc', id: 'cloud/user-guide/connect-database/certified/README'},
                     items:[
                            'cloud/user-guide/connect-database/certified/connect-clickhouse',
                            'cloud/user-guide/connect-database/certified/connect-kafka',
                            'cloud/user-guide/connect-database/certified/connect-mysql',
                            'cloud/user-guide/connect-database/certified/connect-mongodb',
                            'cloud/user-guide/connect-database/certified/connect-oracle',
                            'cloud/user-guide/connect-database/certified/connect-postgresql',
                            'cloud/user-guide/connect-database/certified/connect-sqlserver',
                           ]
                    }, 
                    {
                     type: 'category',
                     label: 'Beta Data Sources',
                     link: {type: 'doc', id: 'cloud/user-guide/connect-database/beta/README'},
                     items:[
                            'cloud/user-guide/connect-database/beta/connect-bigquery',
                            'cloud/user-guide/connect-database/beta/connect-csv',
                            'cloud/user-guide/connect-database/beta/connect-dummy',
                            'cloud/user-guide/connect-database/beta/connect-excel',
                            'cloud/user-guide/connect-database/beta/connect-github',
                            'cloud/user-guide/connect-database/beta/connect-mongodb-atlas',
                            'cloud/user-guide/connect-database/beta/connect-redis',
                            'cloud/user-guide/connect-database/beta/connect-salesforce',
                            'cloud/user-guide/connect-database/beta/connect-selectdb',
                           ]
                    },
                    {
                     type: 'category',
                     label: 'Alpha Data Sources',
                     link: {type: 'doc', id: 'cloud/user-guide/connect-database/alpha/README'},
                     items:[
                            'cloud/user-guide/connect-database/alpha/connect-tablestore',
                            'cloud/user-guide/connect-database/alpha/connect-json',
                            'cloud/user-guide/connect-database/alpha/connect-xml',
                            'cloud/user-guide/connect-database/alpha/connect-zoho',
                           ]
                    }, 
              ]
             },
             'cloud/user-guide/manage-connection',
             {
              type: 'category',
              label: 'Data Replication',
              link: {type: 'doc', id: 'cloud/user-guide/copy-data/README'},
              items:[
                    'cloud/user-guide/copy-data/create-task',
                    'cloud/user-guide/copy-data/manage-task',
                    'cloud/user-guide/copy-data/monitor-task',
                    ]
            },
            {
             type: 'category',
             label: 'Data Development(Beta',
             link: {type: 'doc', id: 'cloud/user-guide/data-development/README'},
             items:[
                   'cloud/user-guide/data-development/create-task',
                   'cloud/user-guide/data-development/manage-task',
                   'cloud/user-guide/data-development/process-node',
                   'cloud/user-guide/data-development/monitor-task',
                   ]
             },
             'cloud/user-guide/custom-node',
             'cloud/user-guide/operation-log',
             {
              type: 'category',
              label: 'Data Console(Beta)',
              link: {type: 'doc', id: 'cloud/user-guide/data-console/README'},
              items:[
                    {
                     type: 'category',
                     label: 'Data Integration Mode',
                     link: {type: 'doc', id: 'cloud/user-guide/data-console/etl-mode/README'},
                     items:[
                            'cloud/user-guide/data-console/etl-mode/etl-mode-dashboard',
                            'cloud/user-guide/data-console/etl-mode/create-etl-task',
                           ]
                    },
                    {
                     type: 'category',
                     label: 'Data Service Platform Model',
                     link: {type: 'doc', id: 'cloud/user-guide/data-console/daas-mode/README'},
                     items:[
                            'cloud/user-guide/data-console/daas-mode/enable-daas-mode',
                            'cloud/user-guide/data-console/daas-mode/daas-mode-dashboard',
                            'cloud/user-guide/data-console/daas-mode/create-daas-task',
                           ]
                    },
                    ]
             },               
             'cloud/user-guide/trouble-shooting-connection',
             'cloud/user-guide/no-supported-data-type',
            ]
    },
    {
     type: 'category',
     label: 'Tutorials',
     link: {type: 'doc', id: 'cloud/best-practice/README'},
     items: [
            'cloud/best-practice/mysql-to-bigquery',
            'cloud/best-practice/oracle-to-tablestore',
            
        ]
        },
     {
      type: 'category',
      label: 'FAQ',
      link: {type: 'doc', id: 'cloud/faq/README'},
      items:[
             'cloud/faq/data-security',
             'cloud/faq/agent-installation',
             'cloud/faq/database',
             'cloud/faq/task',
      ]
     },
     {
      type: 'category',
      label: 'Appendix',
      link: {type: 'doc', id: 'cloud/appendix/README'},
      items: [
              'cloud/appendix/standard-js',
              'cloud/appendix/enhanced-js'
              ]
     },
  ],
};


module.exports = sidebars;
